### ISSUE TITLE
Forvirrende warning om gjensidig manglende outbound access policy

### ISSUE THREAD

**Issue by tronghn** [nais/api#78]
Dersom en applikasjon `foo` har satt opp inbound-regler for en konsument `bar`:

```yaml
spec:
  accessPolicy:
    inbound:
      rules:
        - application: bar
```

og konsumenten `bar` *ikke* har satt opp gjensidige outbound-regler for `foo`, så blir dette vist som en warning hos `foo`i Console:

> Traffic from `bar` in namespace `<namespace>` (`<cluster>`) is allowed by access policy, but `bar` does not have an outbound rule for `foo`.
Consult [Nais Application reference - accessPolicy](https://docs.nais.io/how-to-guides/access-policies/).

Burde dette ha vært en warning hos konsumenten (`bar`) og ikke hos produsenten (`foo`)?

Relevant Slacktråd: https://nav-it.slack.com/archives/C5KUST8N6/p1736151557881179
